config/routes.rb
Rails.application.routes.draw do

  root 'sight#index'

  
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :sight, only: [:show, :index]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sight_controller.rb
class SightController < ApplicationController
require "zabbixapi"


  def index
  	
    @time = Time.now
    
     respond_to do |format|
      format.html
      format.js
    end

  end

  
  def show
   # @movie = Movie.find(params[:id])
   # @cart_action = @movie.cart_action current_user.try :id 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sight_helper.rb
module SightHelper

require "zabbixapi"

def zab(host)
 @zbx = ZabbixApi.connect(
        :url => 'http://zabbix//api_jsonrpc.php',
        :user =>  'operator',
        :password =>  'oper'
    )
 @zbx.graphs.get_ids_by_host(:host => host)

end

def zab2(host)
	
	return "#{host}: "+"Zabbix version: " +@zbx.query(  :method => "apiinfo.version",  :params => {} )
	
end

end

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row ">
  <nav class="top-bar column" data-topbar>

    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            <i class="fi-target"></i> Sight Tamer
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">

      <!-- Right Nav Section -->
    <ul class="right">
     <%if signed_in?%>
       <li><%=link_to current_user.email, edit_user_registration_path%></li>
       <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
     <%else%>
       <li><%=link_to "Register", new_user_registration_path%></li>
       <li><%=link_to "Login", new_user_session_path%></li>
     <%end%>
    </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="has-form">
          <div class="row collapse">
            <!-- <div class="large-8 small-9 columns">
              <input type="text" class="radius-ls expand" placeholder="Find Movie">
            </div>
            <div class="large-4 small-3 columns">
              <a href="#" class=" radius-rs button">Search</a>
            </div> -->
          </div>
        </li>
      </ul>

    </section>

  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <%= render "layouts/alerts" %>
   
    <div id="main-content" class="row full-min-height">
       <%= yield %>
    </div>

    <footer class="row">
     <div class="large-12 columns">
       <hr> <p>© sight tamer 2015</p> 
     </div>
    </footer> 

  
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/sight/index.html.erb
<%if signed_in?%>
  	<p class="row large-12 large-offset-2 zabbix"> <%= zab("osr-redis2") %>  </p>
  	<br>
  	<p class="row large-12 large-offset-2 zabbix"> <%= zab2("osr-redis2") %> </p>
 
<% else %>
	<div id="time" class="row large-12 large-offset-1  ">
	 	 The current time is <%= Time.now  %>
	</div>
	<br>
	<div id="ts" class="row large-12 large-offset-5  ">

		 <%= link_to 'Update Time', data: {Url: sight_index_path(@time)} %> 

	</div>
<%end%>